### PR TITLE
Added priority feature from issues.

### PR DESCRIPTION
**Pull request by vhespanha**
Hey!

I've just added the feature you suggested in the repo issues. From my testing, it seems to be working flawlessly. If you spot any problems with the implementation, I'd be more than happy to fix them.

The diffs include quite a few changes related to formatting and import order. My editor automatically formatted a lot of the files. I felt these changes weren't bad to the repo, so I kept them in. However, if you'd prefer, I can reopen this PR without these formatting changes.

If this gets merged, I'd love to work on some other chores for the repo, like implementing a Makefile similar to the build script you have, along with other stuff that could be automated.

Thanks!

### CODE REVIEW

**Comment by dynnian** [comment]
Thank you for the PR! For my brief testing and some review It's working great. The only thing that still needs to be updated is the help page. If you can add this to finish the PR, I will merge it immediately. Otherwise I will merge it anyway as is and later when I have the time, update it myself.

**Comment by vhespanha** [comment]
Thank you!!

I'll update it first thing in the morning so we can close it.

**Comment by vhespanha** [comment]
Made some more changes besides what you suggested, but here it is!

The help command was using cli-todo instead of clido so i changed it, but if this was intended i can revert it.

**Comment by vhespanha** [comment]
Totally unrelated to this PR, but I'm gonna open a draft of this same CLI using [cobra](https://github.com/spf13/cobra), adding another external dependency might not be what you aim for with the project, but I'll do it so you can take a look at it and decide if you like the idea or not.

**Comment by dynnian** [comment]
Thanks!

> The help command was using cli-todo instead of clido so i changed it, but if this was intended i can revert it.

Nope, that was totally a mistake. cli-todo was a previous name of this tool.

> Totally unrelated to this PR, but I'm gonna open a draft of this same CLI using [cobra](https://github.com/spf13/cobra), adding another external dependency might not be what you aim for with the project, but I'll do it so you can take a look at it and decide if you like the idea or not.

Cobra library looks great, I think it's a great idea.

**Comment by dynnian** [comment]
Merging!

**Comment by dynnian** [comment]
> Totally unrelated to this PR, but I'm gonna open a draft of this same CLI using [cobra](https://github.com/spf13/cobra), adding another external dependency might not be what you aim for with the project, but I'll do it so you can take a look at it and decide if you like the idea or not.

Add an issue with this as a draft. For a next release we can have this, alongside priority and json output.

**Pull request merged**
