### PR TITLE
Cobra Implementation and Project Restructure

### LINKED ISSUE #4: Rewrite the CLI interface using Cobra
[Cobra](https://github.com/spf13/cobra) is a powerful library for building modern CLI applications. It offers a robust and flexible framework that simplifies the management of complex command structures and subcommands. With automatic handling of help generation, flag parsing, and command validation, Cobra allows developers to focus on the application's core functionality rather than the nuances of CLI management. Moreover, Cobra's extensibility and consistent command syntax enhance the development process, making the application more intuitive and scalable as it evolves.

### PR DESCRIPTION
**Pull request by vhespanha**
I implemented a draft version of what I think the tool could be using Cobra to handle the CLI.

These are some big changes to the whole project, hence why I'm opening this as a draft, a lot can be changed to fit your vision of the tool and to refine some of my code too.

## Project Structure

Since Cobra expects a certain project structure, I moved some things around and restructured the project. Here's what it looks like for now:

```
clido/
├── cmd/
│   ├── completion.go
│   ├── edit.go
│   ├── list.go
│   ├── new.go
│   ├── remove.go
│   ├── root.go
│   └── toggle.go
├── internal/
│   └── version/
│       └── version.go
├── pkg/
│   ├── config/
│   │   └── config.go
│   ├── models/
│   │   ├── project.go
│   │   └── task.go
│   ├── repository/
│   │   ├── project_repo.go
│   │   ├── repository.go
│   │   └── task_repo.go
│   └── utils/
│       └── helpers.go
├── .gitignore
├── go.mod
├── go.sum
├── LICENSE
├── main.go
├── Makefile
└── README.md
```

## Changes and Additions

- Reimplemented the commands using Cobra
- Made repository, models, and config their own packages
- Introduced an utils package to place some reusable code, both for now and for when we get the TUI
- Added a Makefile instead of the build.sh
- Bumped the version due to big changes
- Updated the README with installation help

## Notes

- The usability of the tool is basically the same, I took extra care to make the "API" mirror your previous code
- I had some trouble with the tablewriter package, so maybe take extra care when reviewing that part
- The Makefile includes features like formatting and linting

## Issues

Unfortunately, I had to strip most of the colorization from the tool. This was done because the color package became too verbose when used with Cobra. This is probably a big skill issue, but tomorrow I'll take a look at some other CLI colorization tools and mess a little more with the one you used to see if I can learn to use it better with Cobra.

### CODE REVIEW

**Comment by dynnian** [comment]
Man this is amazing, I will take a look at everything later when I got time (I have uni class tomorrow). Thank you for the support. In the meantime if you see anything that needs changing or improving, go on and do it.

Also I'm still learning Go, of course I can understand most of it, but thing is that I plan on implementing a TUI interface as well, just like [geek-life](https://github.com/ajaxray/geek-life), actually this whole project is intended to be a "spiritual" continuation of geek-life, seeing that it's quite abandoned. Another thing that I want to implement and will need massive refactoring of the code, are sub-projects and sub-tasks, basically a hierarchical structure. So I literally don't know if implementing Cobra will have an effect on any of those, I guess not considering geek-life also has a CLI interface that's separate from the main TUI one.

Anyways I will take my time later to review everything. Thank you very much.

**Comment by dynnian** [comment]
> Introduced an utils package to place some reusable code, both for now and for when we get the TUI

I totally missed the TUI part lmao. This is really cool.

**Comment by dynnian** [comment]
Hi! I'm testing the PR a bit, running make gives this error:

```
$ make
go mod download
go get honnef.co/go/tools/cmd/staticcheck
go: downloading golang.org/x/tools v0.12.1-0.20230825192346-2191a27a6dc5
go: downloading golang.org/x/exp/typeparams v0.0.0-20221208152030-732eee02a75a
go: downloading golang.org/x/mod v0.12.0
go: added github.com/BurntSushi/toml v1.2.1
go: added golang.org/x/exp/typeparams v0.0.0-20221208152030-732eee02a75a
go: added golang.org/x/mod v0.12.0
go: added golang.org/x/tools v0.12.1-0.20230825192346-2191a27a6dc5
go: added honnef.co/go/tools v0.4.7
go get mvdan.cc/gofumpt
go: downloading golang.org/x/sync v0.6.0
go: downloading golang.org/x/mod v0.14.0
go: downloading golang.org/x/tools v0.17.0
go: added github.com/google/go-cmp v0.6.0
go: upgraded golang.org/x/mod v0.12.0 => v0.14.0
go: upgraded golang.org/x/sync v0.3.0 => v0.6.0
go: upgraded golang.org/x/tools v0.12.1-0.20230825192346-2191a27a6dc5 => v0.17.0
go: added mvdan.cc/gofumpt v0.6.0
go get golang.org/x/tools/cmd/goimports
go: downloading golang.org/x/tools v0.24.0
go: downloading golang.org/x/mod v0.20.0
go: downloading golang.org/x/sync v0.8.0
go: upgraded golang.org/x/mod v0.14.0 => v0.20.0
go: upgraded golang.org/x/sync v0.6.0 => v0.8.0
go: upgraded golang.org/x/tools v0.17.0 => v0.24.0
go get github.com/segmentio/golines
go: downloading github.com/segmentio/golines v0.12.2
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/dave/dst v0.27.3
go: downloading github.com/fatih/structtag v1.2.0
go: downloading github.com/sirupsen/logrus v1.9.3
go: downloading github.com/x-cray/logrus-prefixed-formatter v0.5.2
go: downloading golang.org/x/term v0.16.0
go: downloading gopkg.in/alecthomas/kingpin.v2 v2.2.6
go: downloading github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751
go: downloading github.com/alecthomas/units v0.0.0-20231202071711-9a357b53e9c9
go: downloading golang.org/x/crypto v0.18.0
go: downloading github.com/mgutz/ansi v0.0.0-20200706080929-d51e80ef957d
go: added github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751
go: added github.com/alecthomas/units v0.0.0-20231202071711-9a357b53e9c9
go: added github.com/dave/dst v0.27.3
go: added github.com/fatih/structtag v1.2.0
go: added github.com/mgutz/ansi v0.0.0-20200706080929-d51e80ef957d
go: added github.com/pmezard/go-difflib v1.0.0
go: added github.com/segmentio/golines v0.12.2
go: added github.com/sirupsen/logrus v1.9.3
go: added github.com/x-cray/logrus-prefixed-formatter v0.5.2
go: added golang.org/x/crypto v0.18.0
go: added golang.org/x/term v0.16.0
go: added gopkg.in/alecthomas/kingpin.v2 v2.2.6
staticcheck ./...
make: staticcheck: No such file or directory
make: *** [Makefile:49: lint] Error 127
```

Something is going on with this:

``` makefile
lint:
	$(STATICCHECK) ./...
```

Apart from that the CLI interface with cobra is really good, I really like the invidivual help pages for each command. Long arguments are great too, I was planning on implementing them. I didn't find any bug in the CLI interface as of now, apart from #6 which is also in the current main branch.

Upon further code review, I find everything well structured and the code looks great, even easier to understand now.

Of course the only regression is colored output, but we can do that later on. For now this is perfect.

**Comment by dynnian** [comment]
> Hi! I'm testing the PR a bit, running make gives this error:
> 
> ```
> $ make
> go mod download
> go get honnef.co/go/tools/cmd/staticcheck
> go: downloading golang.org/x/tools v0.12.1-0.20230825192346-2191a27a6dc5
> go: downloading golang.org/x/exp/typeparams v0.0.0-20221208152030-732eee02a75a
> go: downloading golang.org/x/mod v0.12.0
> go: added github.com/BurntSushi/toml v1.2.1
> go: added golang.org/x/exp/typeparams v0.0.0-20221208152030-732eee02a75a
> go: added golang.org/x/mod v0.12.0
> go: added golang.org/x/tools v0.12.1-0.20230825192346-2191a27a6dc5
> go: added honnef.co/go/tools v0.4.7
> go get mvdan.cc/gofumpt
> go: downloading golang.org/x/sync v0.6.0
> go: downloading golang.org/x/mod v0.14.0
> go: downloading golang.org/x/tools v0.17.0
> go: added github.com/google/go-cmp v0.6.0
> go: upgraded golang.org/x/mod v0.12.0 => v0.14.0
> go: upgraded golang.org/x/sync v0.3.0 => v0.6.0
> go: upgraded golang.org/x/tools v0.12.1-0.20230825192346-2191a27a6dc5 => v0.17.0
> go: added mvdan.cc/gofumpt v0.6.0
> go get golang.org/x/tools/cmd/goimports
> go: downloading golang.org/x/tools v0.24.0
> go: downloading golang.org/x/mod v0.20.0
> go: downloading golang.org/x/sync v0.8.0
> go: upgraded golang.org/x/mod v0.14.0 => v0.20.0
> go: upgraded golang.org/x/sync v0.6.0 => v0.8.0
> go: upgraded golang.org/x/tools v0.17.0 => v0.24.0
> go get github.com/segmentio/golines
> go: downloading github.com/segmentio/golines v0.12.2
> go: downloading github.com/pmezard/go-difflib v1.0.0
> go: downloading github.com/dave/dst v0.27.3
> go: downloading github.com/fatih/structtag v1.2.0
> go: downloading github.com/sirupsen/logrus v1.9.3
> go: downloading github.com/x-cray/logrus-prefixed-formatter v0.5.2
> go: downloading golang.org/x/term v0.16.0
> go: downloading gopkg.in/alecthomas/kingpin.v2 v2.2.6
> go: downloading github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751
> go: downloading github.com/alecthomas/units v0.0.0-20231202071711-9a357b53e9c9
> go: downloading golang.org/x/crypto v0.18.0
> go: downloading github.com/mgutz/ansi v0.0.0-20200706080929-d51e80ef957d
> go: added github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751
> go: added github.com/alecthomas/units v0.0.0-20231202071711-9a357b53e9c9
> go: added github.com/dave/dst v0.27.3
> go: added github.com/fatih/structtag v1.2.0
> go: added github.com/mgutz/ansi v0.0.0-20200706080929-d51e80ef957d
> go: added github.com/pmezard/go-difflib v1.0.0
> go: added github.com/segmentio/golines v0.12.2
> go: added github.com/sirupsen/logrus v1.9.3
> go: added github.com/x-cray/logrus-prefixed-formatter v0.5.2
> go: added golang.org/x/crypto v0.18.0
> go: added golang.org/x/term v0.16.0
> go: added gopkg.in/alecthomas/kingpin.v2 v2.2.6
> staticcheck ./...
> make: staticcheck: No such file or directory
> make: *** [Makefile:49: lint] Error 127
> ```
> 
> Something is going on with this:
> 
> ```makefile
> lint:
> 	$(STATICCHECK) ./...
> ```

After doing `go install <thingy make is complaining about>` and ensuring $GOPATH/bin is in my PATH, I get this:

```
$ make
go mod download
go get honnef.co/go/tools/cmd/staticcheck
go get mvdan.cc/gofumpt
go get golang.org/x/tools/cmd/goimports
go get github.com/segmentio/golines
staticcheck ./...
gofumpt -l -w .
goimports -w .
golines -w .
make: *** No rule to make target 'test', needed by 'all'.  Stop.
```

**Comment by dynnian** [comment]
> After doing `go install <thingy make is complaining about>` and ensuring $GOPATH/bin is in my PATH, I get this:
> 
> ```
> $ make
> go mod download
> go get honnef.co/go/tools/cmd/staticcheck
> go get mvdan.cc/gofumpt
> go get golang.org/x/tools/cmd/goimports
> go get github.com/segmentio/golines
> staticcheck ./...
> gofumpt -l -w .
> goimports -w .
> golines -w .
> make: *** No rule to make target 'test', needed by 'all'.  Stop.
> ```

I added this test target to the Makefile and it fixed the issue. But I think we can skip doing this because we currently don't have any tests defined:

``` makefile
test:
	$(GOTEST) ./...
```

**Comment by vhespanha** [comment]
Hey!! 

I just fixed the problems we had with the Makefile, turns out i was trying to use `go get` instead of `go install` on the needed tools, I fixed it and added some checks to avoid reinstalling the tools every time we run a make command that requires a dependency.

The test part was some leftover stuff from a Makefile boilerplate I got, I remove the command implementation but left `make all` still calling `make test`, when we get some tests I'll add it back. Thanks.

**Comment by dynnian** [comment]
Great, building now works as expected. I'm going to merge it as is now, if we encounter any issue afterwards, we deal with it separately. Amazing work.

**Pull request merged**
